# Configuration File for vpype-mecode

# =====================================================================
# Global Document Settings
# ---------------------------------------------------------------------
# These settings control the machine's behavior and apply to all layers
# unless specifically overridden in a layer section.
# =====================================================================

[document]

# Custom header and footer

header-gcode = "header.gcode"   # Path to a G-code header file
footer-gcode = "footer.gcode"   # Path to a G-code footer file

# Length and time units
length-units = "mm"             # mm (millimeters), in (inches)
time-units = "s"                # s (seconds), ms (milliseconds)

# Component modes specify how to generate the G-Code
head-mode = "standard"          # standard, auto-leveling
tool-mode = "marker"            # beam, adaptive-beam, blade, extruder, heated-extruder, marker, spindle
rack-mode = "manual"            # off, manual, automatic
coolant-mode = "off"            # off, mist, flood
fan-mode = "off"                # off, cooling
bed-mode = "off"                # off, heated

# Tool configuration
tool-number = 1                 # Tool identifier number
spin-mode = "clockwise"         # off, clockwise, counter
spindle-rpm = 1000              # Spindle speed in revolutions per minute
power-mode = "constant"         # off, constant, dynamic
power-level = 50                # Power level for energy-based tools
warmup-delay = 2.0              # Delay after tool start/stop in time units

# Speeds in units per minute
work-speed = "500.0mm"          # Speed during operations
plunge-speed = "100.0mm"        # Speed when tool enters material
travel-speed = "1000.0mm"       # Speed between operations

# Z-axis heights
work-z = "0.0mm"                # Z height during operations
plunge-z = "1.0mm"              # Z height for initial material contact
safe-z = "10.0mm"               # Z height for movements between operations
park-z = "50.0mm"               # Z height when parked

# Extrusion parameters
nozzle-diameter = "0.4mm"       # Diameter of the extruder's noozle
filament-diameter = "1.75mm"    # Diameter of the extruded filament
layer-height = "0.2mm"          # Height of each layer
retract-length = "1.5mm"        # How much filament to retract
retract-speed = "2100mm"        # Speed at which to retract filament

# Heightmap configuration
height-map-path = "map.png"     # Heightmap file path
height-map-scale = 50.0         # Scale of the heightmap
height-map-tolerance = 0.01     # Heightmap sampling tolerance

# Other parameters
fan-speed = 255                 # min = 0, max = 255
bed-temperature = 60            # Celsius degrees
hotend-temperature = 120        # Celsius degrees

# =====================================================================
# Layer-Specific Settings
#
# - Create a new [layer-N] section for each layer.
# - Settings not specified here will inherit from the [document] section.
# - Layers are numbered in the order they appear in the document.
# =====================================================================

[layer-0]

# head-mode = "standard"
# tool-mode = "marker"
# rack-mode = "manual"
# coolant-mode = "off"
# fan-mode = "off"
# bed-mode = "off"
# tool-number = 1
# spin-mode = "clockwise"
# spindle-rpm = 1000
# power-mode = "constant"
# power-level = 50
# warmup-delay = 2.0
# work-speed = "500.0mm"
# plunge-speed = "100.0mm"
# travel-speed = "1000.0mm"
# work-z = "0.0mm"
# plunge-z = "1.0mm"
# safe-z = "10.0mm"
# park-z = "50.0mm"
# nozzle-diameter = "0.4mm"
# filament-diameter = "1.75mm"
# layer-height = "0.2mm"
# retract-length = "1.5mm"
# retract-speed = "2100mm"
# height-map-path = "map.png"
# height-map-scale = 50.0
# height-map-tolerance = 0.01
# fan-speed = 255
# bed-temperature = 60
# hotend-temperature = 120

[layer-1]

# head-mode = "standard"
# tool-mode = "marker"
# rack-mode = "manual"
# coolant-mode = "off"
# fan-mode = "off"
# bed-mode = "off"
# tool-number = 1
# spin-mode = "clockwise"
# spindle-rpm = 1000
# power-mode = "constant"
# power-level = 50
# warmup-delay = 2.0
# work-speed = "500.0mm"
# plunge-speed = "100.0mm"
# travel-speed = "1000.0mm"
# work-z = "0.0mm"
# plunge-z = "1.0mm"
# safe-z = "10.0mm"
# park-z = "50.0mm"
# nozzle-diameter = "0.4mm"
# filament-diameter = "1.75mm"
# layer-height = "0.2mm"
# retract-length = "1.5mm"
# retract-speed = "2100mm"
# height-map-path = "map.png"
# height-map-scale = 50.0
# height-map-tolerance = 0.01
# fan-speed = 255
# bed-temperature = 60
# hotend-temperature = 120

[layer-2]

# head-mode = "standard"
# tool-mode = "marker"
# rack-mode = "manual"
# coolant-mode = "off"
# fan-mode = "off"
# bed-mode = "off"
# tool-number = 1
# spin-mode = "clockwise"
# spindle-rpm = 1000
# power-mode = "constant"
# power-level = 50
# warmup-delay = 2.0
# work-speed = "500.0mm"
# plunge-speed = "100.0mm"
# travel-speed = "1000.0mm"
# work-z = "0.0mm"
# plunge-z = "1.0mm"
# safe-z = "10.0mm"
# park-z = "50.0mm"
# nozzle-diameter = "0.4mm"
# filament-diameter = "1.75mm"
# layer-height = "0.2mm"
# retract-length = "1.5mm"
# retract-speed = "2100mm"
# height-map-path = "map.png"
# height-map-scale = 50.0
# height-map-tolerance = 0.01
# fan-speed = 255
# bed-temperature = 60
# hotend-temperature = 120
