# =====================================================================
# Milling Wood
# =====================================================================

[document]

# Length and time units
length-units = "mm"
time-units = "s"

# Component modes
head-type = "standard"
tool-type = "spindle"
rack-type = "manual"
coolant-type = "off"
fan-type = "off"
bed-type = "off"

# Tool configuration
tool-number = 1
spin-mode = "clockwise"
spindle-rpm = 10000
warmup-delay = 1.0

# Speeds in units per minute
work-speed = "800.0mm"
plunge-speed = "300.0mm"
travel-speed = "1500.0mm"

# Z-axis heights
work-z = "0.0mm"
plunge-z = "1.0mm"
safe-z = "10.0mm"
park-z = "50.0mm"
