# =====================================================================
# Laser Engraving
# =====================================================================

[document]

# Length and time units
length-units = "millimeters"
time-units = "seconds"

# Component modes
head-type = "standard"
tool-type = "adaptive-beam"
rack-type = "manual"
coolant-type = "off"
fan-type = "off"
bed-type = "off"

# Tool configuration
tool-number = 1
power-mode = "dynamic"
power-level = 50.0
warmup-delay = 2.0

# Speeds in units per minute
work-speed = "1000.0mm"
plunge-speed = "100.0mm"
travel-speed = "1200.0mm"

# Z-axis heights
work-z = "0mm"
plunge-z = "0mm"
safe-z = "0mm"
park-z = "0mm"
