# =====================================================================
# 3D Printing ABS
# =====================================================================

[document]

# Length and time units
length-units = "mm"
time-units = "s"

# Component modes
head-type = "standard"
tool-type = "heated-extruder"
rack-type = "off"
coolant-type = "off"
fan-type = "cooling"
bed-type = "heated"

# Tool configuration
power-mode = "constant"
power-level = 50
warmup-delay = 2.0

# Speeds in units per minute
work-speed = "500.0mm"
plunge-speed = "100.0mm"
travel-speed = "1000.0mm"

# Z-axis heights
work-z = "0.0mm"
plunge-z = "1.0mm"
safe-z = "10.0mm"
park-z = "50.0mm"

# Extrusion parameters
nozzle-diameter = "0.4mm"
filament-diameter = "1.75mm"
layer-height = "0.2mm"
retract-length = "1.5mm"
retract-speed = "2100mm"

# Other parameters
fan-speed = 255
bed-temperature = 100
hotend-temperature = 230
